spring:
  # konfigurasi untuk koneksi db
  datasource:
    #driver-class-name: org.postgresql.Driver

    # sesuaikan nama database anda dengan di bawah ini
    url: jdbc:postgresql://localhost:15001/apap_db_2022?useSSL=false&serverTimezone=Asia/Jakarta

    # sesuaikan dengan NAMA dan PASSWORD anda dengan username password di bawah ini
    username: apap_user_2022
    password: secret99

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

    # pembuatan database (create || create-drop || validate || update)
    hibernate.ddl-auto: create

    show-sql: true

  # Templates reloading during development
  thymeleaf:
    prefix: file:src/main/resources/templates/
    cache: false

  # Static resources reloading during development
  web:
    resources:
      static-locations: file:src/main/resources/static/